version: '3.8'

services:
  web:
    image: python:3.10.2-slim
    build:
      context: ./server
    volumes:
    - ./server/:/server
    stop_signal: SIGINT
    depends_on: 
    - mongodb
    networks:
    - network

  mongodb:
    image: mongo:5.0
    volumes:
    - mongodb:/data/db
    networks:
    - network

  caddy:
    image: caddy:2.4.6
    ports:
    # - 80:80
    # - 443:443
    - 5000:5000
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy:/data
    networks:
    - network

secrets:
  mongodb_username:
    file: ./docker/mongodb_username.secret
  mongodb_password:
    file: ./docker/mongodb_password.secret

volumes:
  mongodb:
    external: true
  caddy:
    external: true

networks:
  network:
    internal: false